### ISSUE TITLE
- book 1, fin volume 19 de Kühn

### ISSUE THREAD

**Issue by etymologika** [galenus-verbatim/galenus_cts#1]
Dans le volume 19 de Kühn, il reste à supprimer la balise "book" dans 9 fichiers:
- https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg036/tlg0530.tlg036.verbatim-grc1.xml
- https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg024/tlg0530.tlg024.verbatim-grc1.xml 
- https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg033/tlg0530.tlg033.verbatim-grc1.xml
- https://galenus-verbatim.github.io/galenus_cts/data/tlg0057/tlg106/tlg0057.tlg106.verbatim-grc1.xml
- https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg041/tlg0530.tlg041.verbatim-grc1.xml
- https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg024/tlg0530.tlg024.verbatim-grc1.xml
- https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg045/tlg0530.tlg045.verbatim-grc1.xml
- https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg031/tlg0530.tlg031.verbatim-grc1.xml
- https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg022/tlg0530.tlg022.verbatim-grc1.xml

**Comment by glorieux-f** [comment]
Est-ce un doublon ou une erreur typo ? 
* https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg024/tlg0530.tlg024.verbatim-grc1.xml

Sinon c’est fait pour ces titres
* https://galenus-verbatim.github.io/galenus_cts/data/tlg0057/tlg106/tlg0057.tlg106.verbatim-grc1.xml
* https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg022/tlg0530.tlg022.verbatim-grc1.xml
* https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg024/tlg0530.tlg024.verbatim-grc1.xml
* https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg031/tlg0530.tlg031.verbatim-grc1.xml
* https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg033/tlg0530.tlg033.verbatim-grc1.xml
* https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg036/tlg0530.tlg036.verbatim-grc1.xml
* https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg041/tlg0530.tlg041.verbatim-grc1.xml
* https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg045/tlg0530.tlg045.verbatim-grc1.xml

![image](https://github.com/galenus-verbatim/galenus_cts/assets/5686231/725706f8-1464-470a-9d89-f7fb64df44fb)

Si vous êtes contente, l’issue peut être fermée.

**Comment by etymologika** [comment]
Merci, erreur de ma part, parfait ainsi!
