### ISSUE TITLE
tlg0057.tlg033.verbatim-grc1 micro-correction

### ISSUE THREAD

**Issue by GSCALAS** [galenus-verbatim/galenus_cts#11]
https://galenus-verbatim.github.io/galenus_cts/data/tlg0057/tlg033/tlg0057.tlg033.verbatim-grc1.xml#urn:cts:greekLit:tlg0057.tlg033.verbatim-grc1:1.1

- éliminer liber 1 (inutile)

**Comment by etymologika** [comment]
et changer dans le TEI header, ligne 36,  <idno>urn:cts:greekLit:tlg0057.tlg033.verbatim-grc2</idno en -grc1

**Comment by glorieux-f** [comment]
- “liber” et <idno>, fait
- envoyé sur le scriptorium

**Comment by etymologika** [comment]
merci!
