### ISSUE TITLE
tlg0057.tlg037.verbatim-grc1 rétablir les titres des chapitres + micro-correction

### ISSUE THREAD

**Issue by etymologika** [galenus-verbatim/galenus_cts#15]
https://galenus-verbatim.github.io/galenus_cts/data/tlg0057/tlg033/tlg0057.tlg033.verbatim-grc1.xml
Donner aux titres entre crochets la balise <label type="head">
Ces titres entre crochets se trouvent aux endroits suivants:
Livre I : chapitres sans titre : 1-7, 10-13 ; chapitres avec titre 8-9, 14-37
Livre II : chapitre sans titres 1 et 22; chapitres avec titre 2-21, 23-71 
Livre III : chapitres sans titre 1 ; chapitre avec titre 2-42
Livre IV : tous les chapitres sont sans titre

et changer dans le TEI header, ligne 36, urn:cts:greekLit:tlg0057.tlg037.verbatim-grc2</idno en -grc1

**Comment by glorieux-f** [comment]
https://galenus-verbatim.github.io/galenus_cts/data/tlg0057/tlg037/tlg0057.tlg037.verbatim-grc1.xml
Titres rétablis, et parti au scriptorium

**Comment by etymologika** [comment]
merci!
