### ISSUE TITLE
tlg0530/tlg024 menue correction

### ISSUE THREAD

**Issue by etymologika** [galenus-verbatim/galenus_cts#2]
https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg024/tlg0530.tlg024.verbatim-grc1.xml
chapitre 6 à déplacer de la fin de 19.545 au début de 19.545 K (et supprimer « Κεφ. Στλ » à la 1re ligne de la page 19.545)

**Comment by Ctaaffe** [comment]
treated
