### ISSUE TITLE
tlg0530/tlg045 corrections

### ISSUE THREAD

**Issue by etymologika** [galenus-verbatim/galenus_cts#6]
https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg045/tlg0530.tlg045.verbatim-grc1.xml
déplacer le chapitre 8 de 19.689 à 19.693
supprimer le chapitre 9 en 19.694 (n’existe pas)

attention, les numéros de chapitres comptent pour une ligne, passim!

Liste exhaustive des titres à rétablir comme titres (sans numérotation), ce ne sont pas des citations: attention, certains font 3 lignes! Il faut alors supprimer les “retours à la ligne” isus de la balise <l...> </l>
-	19.643: Περὶ οὐσίας νεφρῶν.
-	19.644: Περὶ σχήματος νεφρῶν.
-	19.646: Περὶ ἐνεργείας νεφρῶν.
-	19.647: Αἰτίαι τοῦ λίθου.
-	19.655:  Ὅτι ἀπὸ τοῦ ἥπατος καὶ τῆς καρδίας φέρεται φλὲψ καὶ ἀρτηρία ἐπὶ τούς. νεφροὺς καὶ ἐμβάλλουσιν εἰς αὐτήν την κοιλότητα αὐτῶν.
-	19.656:  Ὅτι ἐκ τῆς παρατρίψεως τοῦ λίθου πνεύματα δριμέα ἐπιτρέχουσι καὶ ἐρεθίζουσι καὶ ποιοῦσι κνησμὸν, ὥσπερ τῆς φύσεως ἐπιδεικνυούσης τὸν πεπονθότα τόπον. (supprimer les retours à la ligne dans ce titre)
-	19.657: Οἱ μὲν ἰδιῶται όδύνην βαρεῖαν λὲγουσι τήν συναίσθησιν την ἀνιαρὰν, οἱ δὲ ἰατροὶ τήν σφοδροτάτην. (supprimer les retours à la ligne dans ce titre)
-	19.658: Ἐκ τοῦ ἀθρόως φέρεσθαι λίθον περὶ τήν ὀσφύν γίνεσθαι βάρους συναίσθησιν. (supprimer les retours à la ligne dans ce titre)
-	19.661: Θεραπεία τοῦ λίθου καὶ τῶν ἄλλων ἐν τοῖς νεφροῖς παθῶν.
-	19.662: Διὰ τί φλεβοτομοῦμεν πρὸ τῆς καθάρσεως;
-	19.664: Ὅτι ἀπ᾽ ἀγκῶνος μὲν, ἐὰν ἔτι ἐπιρρευματίζηται ὁ νεφρὸς, χρῆ ἀφαιρεῖν τὸ αἷμα · ἀπὸ τῆς ἰγνύος δὲ, ἐὰν στῇ το ἐπιρρεῖν. τήν τε φλέβα τὴν ὑποκάτω τοῦ γόνατος. αὕτη γὰρ ἰσοδυναμεῖ τῇ καθόλου φλεβὶ, εἰ δ᾽ ἀπορήσαις αὐτῆς, ἀποσχίδας αὐτῆς χρή τέμνειν. (supprimer les retours à la ligne dans ce titre)
En revanche, à rétablir comme début d’un § normal (ce n’est pas une citation):
19.655  Τὰ δὲ σπερματικὰ ἀγγεῖα φέρονται ἐπὶ τοὺς ὄρχεις.

**Comment by Ctaaffe** [comment]
done

**Comment by GSCALAS** [comment]
Cahal, j'ai l'impression que : 

- le titre 19.656: Ὅτι ἐκ τῆς παρατρίψεως τοῦ λίθου πνεύματα δριμέα ἐπιτρέχουσι καὶ ἐρεθίζουσι καὶ ποιοῦσι κνησμὸν, ὥσπερ τῆς φύσεως ἐπιδεικνυούσης τὸν πεπονθότα τόπον soit mis comme si c'était une citation, je crois.

- le titre 19.655 Τὰ δὲ σπερματικὰ ἀγγεῖα φέρονται ἐπὶ τοὺς ὄρχεις ne soit pas là.

**Comment by etymologika** [comment]
merci @glorieux-f
