### ISSUE TITLE
 tlg0530/tlg022 corrections

### ISSUE THREAD

**Issue by etymologika** [galenus-verbatim/galenus_cts#7]
https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg022/tlg0530.tlg022.verbatim-grc1.xml
rétablir une ligne pour le chapitre 14 en 19.775 (partout ailleurs, les numéros de chapitres sont bien comptés pour une ligne; mais le chapitre 14 a été rajouté postérieurement, d’où peut-être la différence de traitement??)

Liste exhaustive des titres à rétablir comme titres (sans numérotation):
-	19.748: Τί ο σταθμος, τί τὸ μέτρον καὶ ἀμφοτέρων διαφοραί.
-	19.749: Περὶ τῶν δηλούντων τοὺς σταθμοὺς καὶ τὰ μέτρα χαρακτήρων.
-	19.751: Περὶ σταθμῶν. Περὶ μέτρων ὑγρῶν.
-	19.752:  Περὶ μέτρων ὑγρῶν.
-	19.754:  Τὸ διάγραμμα κεῖται.
-	19.755: Περὶ μέτρων ξηρῶν διδασκαλία σαφής.
-	19.756:  Περὶ σημείων καὶ χαρακτήρων τῶν ἐν ταῖς συσταθμίαις καὶ περὶ σταθμῶν καὶ μέτρων. Ἡ ἄλλη ἔκθεσις.  (fonctionnent comme titre et sous-titre)
-	19.759:  Ἕκθεσις περὶ σταθμῶν καὶ μέτρων ἀκριβεστάτη.
-	19.762:  Ἕτι περὶ μέτρων καὶ σταθμῶν ἰατρικῶν συντομωτάτως ἔκθεσις ἁπλουστάτη.
-	19.764:  Περὶ μέτρων καὶ σταθμῶν.
-	19.767:   Ἐκ τῶν Κλεοπάτρας κοσμητικῶν περὶ σταθμῶν καὶ μέτρων. ι
-	19.771: Ἄλλως περὶ τῶν αὐτῶν.
-	19.772: Περὶ μέτρων καὶ σταθμῶν ἱππιατρικῶν.
-	19.773: Περὶ μέτρων ὑγρῶν.
-	19.775: Διοσκορίδου περὶ μέτρων καὶ σταθμῶν.
-	19.775: Περὶ σταθμῶν.
-	19.776: Περὶ μέτρων ὑγρῶν, οἴνου, ὕδατος καὶ ὄξους.
-	19.777: Ἐλαίου.
-	19.777: Μέλιτος.
-	19.778: Ἄλλως περὶ μέτρων καὶ σταθμῶν.
-	19.780: Περὶ σημείων τῶν μέτρων καὶ σταθμῶν.

**Comment by Ctaaffe** [comment]
que faire pour les sous-titres?

**Comment by Ctaaffe** [comment]
Sinon les sous titres le reste est fait

**Comment by GSCALAS** [comment]
Ligne pour le chapitre 14 en 19.775 rétablie.
En revanche les titres ont encore la numérotation. Ou je me trompe ?

**Comment by Ctaaffe** [comment]
Ligne du chapitre 14 ajouté 
pas de numérotation des titres dans Kühn
