### ISSUE TITLE
tlg0530.tlg041.verbatim-grc1corrections chapitres (sections)

### ISSUE THREAD

**Issue by GSCALAS** [galenus-verbatim/galenus_cts#9]
https://galenus-verbatim.github.io/galenus_cts/data/tlg0530/tlg041/tlg0530.tlg041.verbatim-grc1.xml#urn:cts:greekLit:tlg0530.tlg041.verbatim-grc1:156

[quand j'écris chapitre j'entend section]

1) 19.381 ρκζ . (à éliminer) Ὕπνος ἐστὶν ἄνεσις ψυχῆς κατα φυσιν ἀπὸ τῶν etc n'est pas compté en tant que chapitre (127).

2) 19.395 ροα΄(à éliminer) "Βοηθηματικὰ σημεῖά ἐστιν ἒξ ὦν ὑπομιμνησκόμεθα ㅤτῆς ἐπ᾽ αὐτοῖς τετηρημένης θεραπείας." n'est pas compté en tant que chapitre (171)

3) 19.410 σκδ΄. (à éliminer) Ἐσκολιωμένος ἐστὶν ὁ μὴ ἐπ᾽ εὐθείας τεταγμένης ㅤτῆς ἀρτηρίας ἐπιτελούμενος παρὰ τὴν θέσιν. n'est pas compté en tant que chapitre (224)

4) 19.410 σκἔ. (à éliminer) Μύουρος ἐστιν ό παρὰ τὴν θέσιν ὅταν τὰ μὲν ㅤㅤ ἐπ ἄνω μέρη τῆς ἀρτηρίας συνάγηται, τὰ δὲ κάτω ㅤτοὐναντίον. ἐνταῦθα μὲν ἐπὶ πλέον ἀνευρύνεται, ἐν δὲ τοῖς n'est pas compté en tant que chapitre (225)

5) 19.414 Σλθ . (à éliminer) Ὀπισθότονός ἐστιν ὅταν ὅπισθεν ἕλκηται καὶ ㅤεἰς τοὔμπροσθεν ἀνακλᾶσθαι μὴ δύνηται. ἢ ὀπισθότονός n'est pas compté en tant que chapitre (239)

6) 19.424 σπβ΄. (à éliminer) Νεφρῖτις ἐστὶ φλεγμονὴ νεφρῶν μετ᾽ ἀλγήματος n'est pas compté en tant que chapitre (282)

7) 19.427 σϟα΄. (à éliminer) Ἀρθρῖτις ἐστὶ φλεγμονὴ συνισταμένη περὶ τοῖς ㅤἄρθροις ἔμμονος πόνον ἰσχυρὸν ἐπιφέρουσα πασχόντων ㅤνεύρων. n'est pas compté en tant que chapitre (291)

8) 19.427 σϟβ. (à éliminer ) Ποδαγρα ἐστὶ πάθος περὶ τοῖς ποσὶ γιγνόμενον etc n'est pas compté en tant que chapitre (292)

9) 19.427 σϟγ. (à éliminer) Σκελοτύρβη ἐστὶν εἶδος παραλύσεως ὥστε περιπατεῖν n'est pas compté en tant que chapitre (293)

10) 19.427 σϟδ᾽.(à éliminer) Πήρωσίς ἐντι στέρησις ἢ ἐμποδισμὸς n'est pas compté en tant que chapitre (294)

11) 19.427 σϟε΄. (à éliminer) Λέπρα ἐστὶ μεταβολὴ τοῦ χρωτὸς ἐπὶ τὸ παρὰ n'est pas compté en tant que chapitre (295)

12) 19.428 σϟσε΄. (à éliminer)  Ἐλεφάς ἐστι πάθος παχὺ τὸ δέρμα καὶ ἀνὠμαλον n'est pas compté en tant que chapitre (296)

13) 19.428 σϟζ᾽. (à éliminer) Λειχήν εστι τραχύτης ἐπιφανείας μετὰ πολλοῦ ㅤκνησμοῦ. n'est pas compté en tant que chapitre (297)

14) 19.428 σϟή. (à éliminer) Φλεγμονή ἐστιν ἐν μἦτρφ ἡ μετὰ πόνου γιγνομένη ㅤἐπιγαστρίου καὶ βουβώνων καὶ πυρετῶν ἒξ ης καὶ ㅤβρέγματος πόνος καὶ τενόντων συνολκὴ καὶ ὸφθαλμῶν ὀδύνη. n'est pas compté en tant que chapitre(298)

15) 19.428 σϟθ . (à éliminer) Αποστημα ἐν μητρηι ἐστὶν ὅταν ῃ πόνος ἐπιτεταμένος ㅤκαὶ σφυζει καὶ διατείνει τὸ ἄλγημα ἕως ἤτρου καὶ ㅤβουβώνων καὶ ὀσφύος καὶ πυρετοὶ προσγίνονται. n'est pas compté en tant que chapitre (299)

16) 19.428 τ᾽. (à éliminer) Ῥστερικη πνίξ ἐστι παθος δι᾽ ἀναδρομην υστέρας ㅤγιγνομενον η καταπτωσιν καὶ ἀφωνίαν ἐπιφέρει. ὥστε καὶ ㅤτήν ἀναπνοὴν αὐταῖς οὐκ ἔκδηλον γίγνεσθαι, μετεωρίζεσθαί n'est pas compté en tant que chapitre (300)

17) 19.429 τα; (à éliminer) Γυναικεῖος ῥοῦς ἐστι φορὰ ὑγρῶν διὰ μήτρας ἐπὶ n'est pas compté en tant que chapitre (301)

18) 19.429 τβ΄. (à éliminer) Ἐρυσίπελας ἐν μήτρα ἐστὶν ἐπειδὰν ὀδυνωμένη ἡ n'est pas compté en tant que chapitre (302)

19) 19.429 τγ᾽. (à éliminer) Σκλήρωμα ἐν μήτρα ἐστὶν ὄγκος ὑπόσκληρος περί n'est pas compté en tant que chapitre (303)

20) 19.435 τιό. (à éliminer) Μυδρίασίς ἐστιν ἀμαύρωσις .τοῦ ὁρατικοῦ ταραχθέντων τῶν υγρῶν. n'est pas compté en tant que chapitre (340)

21) 19.436 ㅤτώ. (à éliminer) Χήμωσίς έστιν επαρμα τοῦ περιοφθαλμίου ὑμένος ㅤὅ καὶ λευκὸν προσαγορεύουσι πάθοςὶ ὅμοιον λευκῇ σαρκί. n'est pas compté en tant que chapitre (350)

22) 19.440 τοε΄. (à éliminer) Ἀθέρωμά ἐστι χιτών νευρώδης ἀθερῶδες ὑγρὸν περιέχον. n'est pas compté en tant que chapitre (375)

23) 19.440 τοστ. (à éliminer) Στεάτωμά ἐστι παρὰ φύσιν πιμελῆς συναύξησις. n'est pas compté en tant que chapitre (376)

24) 19.442 τπε . (à éliminer) Σκίῤῥος ἐστὶν ὄγκος σωματων μετὰ σκληρίας καὶ ㅤβαρους καὶ δυσκινησίας τε καὶ δυσαισθησίας. n'est pas compté en tant que chapitre (385)

25) 19.444 υρ᾽.(à éliminer) Γυναικόμασθόν ἐστι παρὰ φύσιν αὔξησις τῆς ㅤὑποκειμένης τοῖς μασθοῖς πιμελῆς. n'est pas compté en tant que chapitre (403)

26) 19.445 υια . (à éliminer) Εν κατακαλύψει ἐστὶν αποστημα τῶν ἐν βάθει ㅤσωμάτων ἢ σπλάγχνων εἰς πύον τῆς μεταβολῆς γινομένης n'est pas compté en tant que chapitre (411)

**Comment by glorieux-f** [comment]
Sectionnement et numérotation corrigées. J’espère que ça ne vous a pas co^té de compté, mais ce fut très utile pour vérifier. Envoyé au scriptorium

**Comment by etymologika** [comment]
merci!
